# Generated by Django 3.1.4 on 2021-01-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='noname', max_length=64)),
                ('note', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
